import type { IEmployee } from '@/entities'
import { ESpecs } from '@/entities'

export const getEmployees = (): IEmployee[] => {
    return [
        { employeeId: 1, employeeFio: 'Иванов Иван Иванович', employeeSpec: ESpecs.SOFTWARE_ENGINEER, employeeDepartment: 'Разработка ПО', employeePhone: '+7 900 123-45-67', employeeLink: 'https://example.com/ivanov', employeeEmail: 'ivanov@example.com' },
        { employeeId: 2, employeeFio: 'Петров Петр Петрович', employeeSpec: ESpecs.FRONTEND_DEVELOPER, employeeDepartment: 'Веб-разработка', employeePhone: '+7 900 234-56-78', employeeLink: 'https://example.com/petrov', employeeEmail: 'petrov@example.com' },
        { employeeId: 3, employeeFio: 'Сидорова Мария Ивановна', employeeSpec: ESpecs.BACKEND_DEVELOPER, employeeDepartment: 'Серверная разработка', employeePhone: '+7 900 345-67-89', employeeLink: 'https://example.com/sidorova', employeeEmail: 'sidorova@example.com' },
        { employeeId: 4, employeeFio: 'Кузнецов Алексей Сергеевич', employeeSpec: ESpecs.FULL_STACK_DEVELOPER, employeeDepartment: 'Полный стек', employeePhone: '+7 900 456-78-90', employeeLink: 'https://example.com/kuznetsov', employeeEmail: 'kuznetsov@example.com' },
        { employeeId: 5, employeeFio: 'Смирнова Анна Викторовна', employeeSpec: ESpecs.DEVOPS_ENGINEER, employeeDepartment: 'DevOps', employeePhone: '+7 900 567-89-01', employeeLink: 'https://example.com/smirnova', employeeEmail: 'smirnova@example.com' },
        { employeeId: 6, employeeFio: 'Волков Дмитрий Андреевич', employeeSpec: ESpecs.QA_ENGINEER, employeeDepartment: 'Тестирование', employeePhone: '+7 900 678-90-12', employeeLink: 'https://example.com/volkov', employeeEmail: 'volkov@example.com' },
        { employeeId: 7, employeeFio: 'Крылова Елена Олеговна', employeeSpec: ESpecs.PRODUCT_MANAGER, employeeDepartment: 'Менеджмент продукта', employeePhone: '+7 900 789-01-23', employeeLink: 'https://example.com/krylova', employeeEmail: 'krylova@example.com' },
        { employeeId: 8, employeeFio: 'Орлов Николай Иванович', employeeSpec: ESpecs.UX_UI_DESIGNER, employeeDepartment: 'Дизайн', employeePhone: '+7 900 890-12-34', employeeLink: 'https://example.com/orlov', employeeEmail: 'orlov@example.com' },
        { employeeId: 9, employeeFio: 'Тимофеев Виктор Евгеньевич', employeeSpec: ESpecs.SYSTEM_ADMINISTRATOR, employeeDepartment: 'Системное администрирование', employeePhone: '+7 900 901-23-45', employeeLink: 'https://example.com/timofeev', employeeEmail: 'timofeev@example.com' },
        { employeeId: 10, employeeFio: 'Зайцева Ольга Михайловна', employeeSpec: ESpecs.DATA_SCIENTIST, employeeDepartment: 'Анализ данных', employeePhone: '+7 900 012-34-56', employeeLink: 'https://example.com/zaytseva', employeeEmail: 'zaytseva@example.com' },
        { employeeId: 11, employeeFio: 'Михайлов Артем Павлович', employeeSpec: ESpecs.DATABASE_ADMINISTRATOR, employeeDepartment: 'Администрирование баз данных', employeePhone: '+7 900 234-65-78', employeeLink: 'https://example.com/mikhailov', employeeEmail: 'mikhailov@example.com' },
        { employeeId: 12, employeeFio: 'Попова Наталья Алексеевна', employeeSpec: ESpecs.NETWORK_ENGINEER, employeeDepartment: 'Сетевое администрирование', employeePhone: '+7 900 345-76-89', employeeLink: 'https://example.com/popova', employeeEmail: 'popova@example.com' },
        { employeeId: 13, employeeFio: 'Егоров Игорь Викторович', employeeSpec: ESpecs.SECURITY_ANALYST, employeeDepartment: 'Информационная безопасность', employeePhone: '+7 900 456-87-90', employeeLink: 'https://example.com/egorov', employeeEmail: 'egorov@example.com' },
        { employeeId: 14, employeeFio: 'Андреева Оксана Владимировна', employeeSpec: ESpecs.TECHNICAL_SUPPORT, employeeDepartment: 'Техническая поддержка', employeePhone: '+7 900 567-98-01', employeeLink: 'https://example.com/andreeva', employeeEmail: 'andreeva@example.com' },
        { employeeId: 15, employeeFio: 'Романов Павел Сергеевич', employeeSpec: ESpecs.PROJECT_MANAGER, employeeDepartment: 'Управление проектами', employeePhone: '+7 900 678-09-12', employeeLink: 'https://example.com/romanov', employeeEmail: 'romanov@example.com' },
        { employeeId: 16, employeeFio: 'Федорова Екатерина Викторовна', employeeSpec: ESpecs.BUSINESS_ANALYST, employeeDepartment: 'Бизнес-анализ', employeePhone: '+7 900 789-10-23', employeeLink: 'https://example.com/fedorova', employeeEmail: 'fedorova@example.com' },
        { employeeId: 17, employeeFio: 'Борисов Сергей Олегович', employeeSpec: ESpecs.SOFTWARE_ENGINEER, employeeDepartment: 'Разработка ПО', employeePhone: '+7 900 890-21-34', employeeLink: 'https://example.com/borisov', employeeEmail: 'borisov@example.com' },
        { employeeId: 18, employeeFio: 'Тарасова Ольга Николаевна', employeeSpec: ESpecs.UX_UI_DESIGNER, employeeDepartment: 'Дизайн', employeePhone: '+7 900 901-32-45', employeeLink: 'https://example.com/tarasova', employeeEmail: 'tarasova@example.com' },
        { employeeId: 19, employeeFio: 'Николаев Илья Павлович', employeeSpec: ESpecs.FRONTEND_DEVELOPER, employeeDepartment: 'Веб-разработка', employeePhone: '+7 900 012-43-56', employeeLink: 'https://example.com/nikolaev', employeeEmail: 'nikolaev@example.com' },
        { employeeId: 20, employeeFio: 'Шевченко Светлана Ивановна', employeeSpec: ESpecs.QA_ENGINEER, employeeDepartment: 'Тестирование', employeePhone: '+7 900 123-54-67', employeeLink: 'https://example.com/shevchenko', employeeEmail: 'shevchenko@example.com' },
        { employeeId: 21, employeeFio: 'Кириллов Андрей Дмитриевич', employeeSpec: ESpecs.SYSTEM_ADMINISTRATOR, employeeDepartment: 'Системное администрирование', employeePhone: '+7 900 234-65-78', employeeLink: 'https://example.com/kirillov', employeeEmail: 'kirillov@example.com' },
        { employeeId: 22, employeeFio: 'Максимова Елена Сергеевна', employeeSpec: ESpecs.DEVOPS_ENGINEER, employeeDepartment: 'DevOps', employeePhone: '+7 900 345-76-89', employeeLink: 'https://example.com/maksimova', employeeEmail: 'maksimova@example.com' },
        { employeeId: 23, employeeFio: 'Григорьев Виктор Олегович', employeeSpec: ESpecs.BUSINESS_ANALYST, employeeDepartment: 'Бизнес-анализ', employeePhone: '+7 900 456-87-90', employeeLink: 'https://example.com/grigoryev', employeeEmail: 'grigoryev@example.com' },
        { employeeId: 24, employeeFio: 'Соколова Татьяна Владимировна', employeeSpec: ESpecs.PRODUCT_MANAGER, employeeDepartment: 'Менеджмент продукта', employeePhone: '+7 900 567-98-01', employeeLink: 'https://example.com/sokolova', employeeEmail: 'sokolova@example.com' },
        { employeeId: 25, employeeFio: 'Сергеев Алексей Александрович', employeeSpec: ESpecs.NETWORK_ENGINEER, employeeDepartment: 'Сетевое администрирование', employeePhone: '+7 900 678-09-12', employeeLink: 'https://example.com/sergeev', employeeEmail: 'sergeev@example.com' },
        { employeeId: 26, employeeFio: 'Павлова Марина Владимировна', employeeSpec: ESpecs.SECURITY_ANALYST, employeeDepartment: 'Информационная безопасность', employeePhone: '+7 900 789-10-23', employeeLink: 'https://example.com/pavlova', employeeEmail: 'pavlova@example.com' },
        { employeeId: 27, employeeFio: 'Коновалов Виктор Дмитриевич', employeeSpec: ESpecs.DATABASE_ADMINISTRATOR, employeeDepartment: 'Администрирование баз данных', employeePhone: '+7 900 890-21-34', employeeLink: 'https://example.com/konovalov', employeeEmail: 'konovalov@example.com' },
        { employeeId: 28, employeeFio: 'Жукова Анна Викторовна', employeeSpec: ESpecs.PROJECT_MANAGER, employeeDepartment: 'Управление проектами', employeePhone: '+7 900 901-32-45', employeeLink: 'https://example.com/zhukova', employeeEmail: 'zhukova@example.com' },
        { employeeId: 29, employeeFio: 'Лебедев Игорь Олегович', employeeSpec: ESpecs.SOFTWARE_ENGINEER, employeeDepartment: 'Разработка ПО', employeePhone: '+7 900 012-43-56', employeeLink: 'https://example.com/lebedev', employeeEmail: 'lebedev@example.com' },
        { employeeId: 30, employeeFio: 'Новикова Татьяна Петровна', employeeSpec: ESpecs.TECHNICAL_SUPPORT, employeeDepartment: 'Техническая поддержка', employeePhone: '+7 900 123-54-67', employeeLink: 'https://example.com/novikova', employeeEmail: 'novikova@example.com' },
    ];
};
