name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Log in to Custom Docker Registry
        uses: docker/login-action@v2
        with:
          registry: git.theomnia.ru
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.prod -t git.theomnia.ru/${{vars.PROJECT_NAME}}/em-symhony:latest .          

      - name: Push Docker image
        run: |
          docker push git.theomnia.ru/${{vars.PROJECT_NAME}}/em-symhony:latest          

      - name: Настройка SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{vars.SSH_HOST}} >> ~/.ssh/known_hosts          

      - name: Выполнение команды make deploy
        run: ssh ${{vars.SSH_USER}}@${{vars.SSH_HOST}} "cd /home/omnia && make deploy"