export enum EActions {
    ADD_OFFICE,
    EDIT_OFFICE,
    DELETE_OFFICE,

    ADD_EMPLOYEE,
    EDIT_EMPLOYEE,
    DELETE_EMPLOYEE,
    IMPORT_EMPLOYEE,

    ADD_EQUIPMENT,
    IMPORT_EQUIPMENT,
    EDIT_EQUIPMENT,
    DELETE_EQUIPMENT,

    ADD_RECORD,
    IMPORT_RECORD,
    EDIT_RECORD,
    DELETE_RECORD,
}
